### ISSUE TITLE
KLBDELETE* macro body should be wrapped by do { ... } while(0)

### ISSUE THREAD

**Issue by zaki50** [KLab/PlaygroundOSS#44]
current definition
# define KLBDELETE(a) if( (a) != NULL ) { .... }

KLBDELETE() does not require semicolon and easily leads to dangling else problem.

It should be
# define KLBDELETE(a) do { if( (a) != NULL ) { .... } } while(0)

**Comment by zaki50** [comment]
See http://kernelnewbies.org/FAQ/DoWhile0

**Comment by muojp** [comment]
working fine.
